import type { AbstractPowerSyncDatabase } from '@powersync/web';
import { uuid } from '../lib/utils';
import type { Paise } from '../lib/money';

export interface PostLine {
  accountId: string;
  /** positive = debit, negative = credit */
  amount: Paise;
  partyId?: string | null;
}

export interface PostEntryInput {
  date: string; // YYYY-MM-DD
  memo: string;
  sourceType: string;
  sourceId: string;
  lines: PostLine[];
}

type Tx = Parameters<Parameters<AbstractPowerSyncDatabase['writeTransaction']>[0]>[0];

/**
 * Posting engine: writes a balanced journal entry inside an existing
 * write transaction. Every business event goes through here so the
 * General Ledger, Trial Balance and Balance Sheet are always consistent.
 */
export async function postEntry(tx: Tx, input: PostEntryInput): Promise<string> {
  const lines = input.lines.filter((l) => l.amount !== 0);
  const sum = lines.reduce((s, l) => s + l.amount, 0);
  if (sum !== 0) {
    throw new Error(`Unbalanced journal entry for ${input.sourceType}/${input.sourceId}: ${sum}`);
  }
  const entryId = uuid();
  const now = new Date().toISOString();
  await tx.execute(
    `INSERT INTO journal_entries (id, date, memo, source_type, source_id, created_at)
     VALUES (?, ?, ?, ?, ?, ?)`,
    [entryId, input.date, input.memo, input.sourceType, input.sourceId, now],
  );
  for (const line of lines) {
    await tx.execute(
      `INSERT INTO journal_lines (id, entry_id, account_id, amount, party_id, date)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [uuid(), entryId, line.accountId, line.amount, line.partyId ?? null, input.date],
    );
  }
  return entryId;
}

/** Remove all journal entries (and lines) generated by a source document. */
export async function unpostSource(tx: Tx, sourceType: string, sourceId: string) {
  await tx.execute(
    `DELETE FROM journal_lines WHERE entry_id IN
       (SELECT id FROM journal_entries WHERE source_type = ? AND source_id = ?)`,
    [sourceType, sourceId],
  );
  await tx.execute(`DELETE FROM journal_entries WHERE source_type = ? AND source_id = ?`, [
    sourceType,
    sourceId,
  ]);
}
